# Exploratory Data Analysis in R

## Install Necessary Libraries

```{r}
install.packages("ggplot2")
```

## Load Necessary libraries

```{r}
library(ggplot2)
library(dplyr)
```

## 1. Read data from a CSV file

```{r}
yield_data <- read.csv("data.csv")

production <- yield_data$Produção..Toneladas.
```

## 2. Exploratory Data Analysis

```{r}
# Measures of Central Tendency
mean_yield <- mean(production)
median_yield <- median(production)
mode_yield <- as.numeric(names(sort(table(production), decreasing = TRUE)[1]))

cat("Mean:", mean_yield, "\n")
cat("Median:", median_yield, "\n")
cat("Mode:", mode_yield, "\n")

# Measures of Dispersion
sd_yield <- sd(production)  # Standard deviation
variance_yield <- var(production)  # Variance
range_yield <- range(production)  # Range (minimum and maximum)
amplitude_yield <- diff(range_yield)  # Absolute range

cat("Standard Deviation:", sd_yield, "\n")
cat("Variance:", variance_yield, "\n")
cat("Range:", amplitude_yield, "\n")

# Separating Measures
quartiles_yield <- quantile(production, probs = c(0.25, 0.5, 0.75))  # Quartiles
percentiles_yield <- quantile(production, probs = seq(0.1, 1, by = 0.1))  # Deciles or Percentiles

cat("Quartiles:", quartiles_yield, "\n")
cat("Percentiles (Deciles):", percentiles_yield, "\n")
```

## 3. Graphical Analysis

```{r}
# Pie chart for the production (in percentage) of each culture type

total_production <- yield_data %>%
  group_by(Tipo.de.Cultura) %>%
  summarise(total_production = sum(Produção..Toneladas.))

# Calculate the percentage of total production for each culture type
total_production <- total_production %>%
  mutate(percentage = total_production / sum(total_production) * 100)

head(total_production)

# Create the pie chart
ggplot(total_production, aes(x = "", y = percentage, fill = Tipo.de.Cultura)) +
  geom_bar(stat = "identity", width = 1) +
  coord_polar("y", start = 0) +
  labs(title = "Produção por Tipo de Cultura", fill = "Tipo de Cultura") +
  theme_minimal() +
  theme(legend.position = "right") +
  geom_text(aes(label = paste(Tipo.de.Cultura, " (", round(percentage, 1), "%)")), position = position_stack(vjust = 0.5))

cat("Exploratory analysis completed.\n")
```
